# Generated by Django 4.0.3 on 2022-04-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=2000)),
                ('img_url', models.CharField(default='na', max_length=5000)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
